apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: magicmagic
  namespace: fleet-default 
spec:
  cloud-config:
    write_files:
    - content: |
        # My new /etc/testcloudconfig file
        # You should be able to see me :-)
      path: /etc/testcloudconfig
