apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: template-seed-image
  namespace: fleet-default
spec:
  baseImage: registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-teal-iso/5.3:1.1.5
  cloud-config:
  cleanupAfterMinutes: 60
  registrationRef:
    name: seedimageregistrationendpoint
    namespace: fleet-default
  retriggerBuild: false
