apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: iso-image-reg-elemental-re01-composite
  namespace: fleet-default
spec:
  baseImage: registry.suse.com/rancher/elemental-teal-iso/5.4:1.2.3
  cloud-config:
  cleanupAfterMinutes: 60
  registrationRef:
    name: elemental-re03
    namespace: fleet-default
  retriggerBuild: false
