apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: magicmagic
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
      - name: root
        passwd: root
    elemental:
      install:
        debug: true
        device: /dev/sda
        poweroff: true
      registration:
        auth: tpm
        emulate-tpm: true
