apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base_image.yaml
- endpoint.yaml

patches:
- path: name_patch.yaml
  target:
    group: elemental.cattle.io
    kind: SeedImage
    version: v1beta1

  